# Generated by Django 2.0.6 on 2019-03-08 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BootCRUDApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagesellmodel',
            name='foreignkeyToUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
