# Generated by Django 2.0.6 on 2019-03-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BootCRUDApp', '0003_auto_20190308_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garbagesellmodel',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='garbagesellmodel',
            name='foreignkeyToUser',
        ),
    ]
